name: EconomyTax
main: onebone\economytax\EconomyTax
author: onebone
version: "2.0.3"
api:
- 3.0.0-ALPHA10

depend: [EconomyAPI]
permissions:
 economytax.tax.avoid:
  description: The permission that allows player to avoid paying tax
  deafault: op
